<?php

use Illuminate\Database\Seeder;
use Admin\Models\Currency;

class CurrencyTableSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('currencies')->delete();
		DB::unprepared("ALTER TABLE currencies AUTO_INCREMENT = 1;");
		$currency = [
'1' => ['country_id' => 1, 'name' => 'Leke', 'code' => 'ALL', 'symbol' => 'Lek', 'symbol_unicode' => 'Lek', 'position' => '', 'separator' => '.' ],
'2' => ['country_id' => 2, 'name' => 'Dollars', 'code' => 'USD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'3' => ['country_id' => 3, 'name' => 'Afghanis', 'code' => 'AFN', 'symbol' => 'Ø‹', 'symbol_unicode' => '&#1547;', 'position' => '', 'separator' => '.' ],
'4' => ['country_id' => 4, 'name' => 'Pesos', 'code' => 'ARS', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'5' => ['country_id' => 5, 'name' => 'Guilders', 'code' => 'AWG', 'symbol' => 'Æ’', 'symbol_unicode' => '&fnof;', 'position' => '', 'separator' => '.' ],
'6' => ['country_id' => 6, 'name' => 'Dollars', 'code' => 'AUD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'7' => ['country_id' => 7, 'name' => 'New Manats', 'code' => 'AZN', 'symbol' => 'AZN', 'symbol_unicode' => 'AZN', 'position' => '', 'separator' => '.' ],
'8' => ['country_id' => 8, 'name' => 'Dollars', 'code' => 'BSD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'9' => ['country_id' => 9, 'name' => 'Dinar', 'code' => 'BHA', 'symbol' => 'Ø¯ÙŠÙ†Ø§Ø±', 'symbol_unicode' => '&#x062F;&#x064A;&#x0646;&#x0627;&#x0631;', 'position' => 'after', 'separator' => '' ],
'10' => ['country_id' => 10, 'name' => 'Dollars', 'code' => 'BBD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'11' => ['country_id' => 11, 'name' => 'Rubles', 'code' => 'BYR', 'symbol' => 'p.', 'symbol_unicode' => 'p.', 'position' => '', 'separator' => '.' ],
'12' => ['country_id' => 12, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => '.' ],
'13' => ['country_id' => 13, 'name' => 'Dollars', 'code' => 'BZD', 'symbol' => 'BZ$', 'symbol_unicode' => 'BZ&#36;', 'position' => '', 'separator' => '.' ],
'14' => ['country_id' => 14, 'name' => 'Dollars', 'code' => 'BMD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'15' => ['country_id' => 15, 'name' => 'Bolivianos', 'code' => 'BOB', 'symbol' => '$b', 'symbol_unicode' => '&#36;b', 'position' => '', 'separator' => '.' ],
'16' => ['country_id' => 16, 'name' => 'Convertible Marka', 'code' => 'BAM', 'symbol' => 'KM', 'symbol_unicode' => 'KM', 'position' => 'before', 'separator' => '.' ],
'17' => ['country_id' => 17, 'name' => 'Pulas', 'code' => 'BWP', 'symbol' => 'P', 'symbol_unicode' => 'P', 'position' => '', 'separator' => '.' ],
'18' => ['country_id' => 18, 'name' => 'Leva', 'code' => 'BGN', 'symbol' => 'Ð»Ð²', 'symbol_unicode' => '&#1083;&#1074;', 'position' => '', 'separator' => '.' ],
'19' => ['country_id' => 19, 'name' => 'Reais', 'code' => 'BRL', 'symbol' => 'R$', 'symbol_unicode' => 'R&#36;', 'position' => 'before', 'separator' => '.' ],
'20' => ['country_id' => 20, 'name' => 'Pounds', 'code' => 'GBP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'21' => ['country_id' => 21, 'name' => 'Dollars', 'code' => 'BND', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'22' => ['country_id' => 22, 'name' => 'Riels', 'code' => 'KHR', 'symbol' => 'áŸ›', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'23' => ['country_id' => 23, 'name' => 'Dollars', 'code' => 'CAD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'24' => ['country_id' => 24, 'name' => 'Dollars', 'code' => 'KYD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'25' => ['country_id' => 25, 'name' => 'Pesos', 'code' => 'CLP', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'26' => ['country_id' => 26, 'name' => 'Yuan Renminbi', 'code' => 'CNY', 'symbol' => 'Â¥', 'symbol_unicode' => '&#165;', 'position' => 'before', 'separator' => '.' ],
'27' => ['country_id' => 27, 'name' => 'Pesos', 'code' => 'COP', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'28' => ['country_id' => 28, 'name' => 'ColÃ³n', 'code' => 'CRC', 'symbol' => 'â‚¡', 'symbol_unicode' => '&#x20A1;', 'position' => 'before', 'separator' => '.' ],
'29' => ['country_id' => 29, 'name' => 'Kuna', 'code' => 'HRK', 'symbol' => 'kn', 'symbol_unicode' => 'kn', 'position' => 'before', 'separator' => '.' ],
'30' => ['country_id' => 30, 'name' => 'Pesos', 'code' => 'CUP', 'symbol' => 'â‚±', 'symbol_unicode' => '&#8369;', 'position' => '', 'separator' => '.' ],
'31' => ['country_id' => 31, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => ',' ],
'32' => ['country_id' => 32, 'name' => 'Koruny', 'code' => 'CZK', 'symbol' => 'KÄ', 'symbol_unicode' => 'K&#269;', 'position' => 'after', 'separator' => '.' ],
'33' => ['country_id' => 33, 'name' => 'Kroner', 'code' => 'DKK', 'symbol' => 'kr', 'symbol_unicode' => 'kr', 'position' => 'before', 'separator' => '.' ],
'34' => ['country_id' => 34, 'name' => 'Pesos', 'code' => 'DOP ', 'symbol' => 'RD$', 'symbol_unicode' => 'RD&#36;', 'position' => '', 'separator' => '.' ],
'35' => ['country_id' => 35, 'name' => 'Dollars', 'code' => 'XCD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'36' => ['country_id' => 36, 'name' => 'Pounds', 'code' => 'EGP', 'symbol' => 'Â£', 'symbol_unicode' => '&#163;', 'position' => 'before', 'separator' => '.' ],
'37' => ['country_id' => 37, 'name' => 'Colones', 'code' => 'SVC', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'38' => ['country_id' => 38, 'name' =>  'Pounds', 'code' =>  'GBP', 'symbol' => 'Â£', 'symbol_unicode' => '&#163;', 'position' => 'before', 'separator' => '.' ],
'39' => ['country_id' => 39, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => ',' ],
'40' => ['country_id' => 40, 'name' => 'Pounds', 'code' => 'FKP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'41' => ['country_id' => 41, 'name' => 'Dollars', 'code' => 'FJD', 'symbol' => '$', 'symbol_unicode' => 'FJ&#36;', 'position' => 'before', 'separator' => '.' ],
'42' => ['country_id' => 42, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => '.' ],
'43' => ['country_id' => 43, 'name' => 'Cedis', 'code' => 'GHC', 'symbol' => 'Â¢', 'symbol_unicode' => '&cent;', 'position' => '', 'separator' => '.' ],
'44' => ['country_id' => 44, 'name' => 'Pounds', 'code' => 'GIP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'45' => ['country_id' => 45, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => ',' ],
'46' => ['country_id' => 46, 'name' => 'Quetzales', 'code' => 'GTQ', 'symbol' => 'Q', 'symbol_unicode' => 'Q', 'position' => 'before', 'separator' => '.' ],
'47' => ['country_id' => 47, 'name' => 'Pounds', 'code' => 'GGP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'48' => ['country_id' => 48, 'name' => 'Dollars', 'code' => 'GYD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'49' => ['country_id' => 49, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => ',' ],
'50' => ['country_id' => 50, 'name' => 'Lempiras', 'code' => 'HNL', 'symbol' => 'L', 'symbol_unicode' => 'L', 'position' => '', 'separator' => '.' ],
'51' => ['country_id' => 51, 'name' => 'Dollars', 'code' => 'HKD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'52' => ['country_id' => 52, 'name' => 'Forint', 'code' => 'HUF', 'symbol' => 'Ft', 'symbol_unicode' => 'Ft', 'position' => 'before', 'separator' => '.' ],
'53' => ['country_id' => 53, 'name' => 'Kronur', 'code' => 'ISK', 'symbol' => 'kr', 'symbol_unicode' => 'kr', 'position' => '', 'separator' => '.' ],
'54' => ['country_id' => 54, 'name' => 'Rupees', 'code' => 'INR', 'symbol' => 'â‚¹', 'symbol_unicode' => '&#8377;', 'position' => 'before', 'separator' => '.' ],
'55' => ['country_id' => 55, 'name' => 'Rupiahs', 'code' => 'IDR', 'symbol' => 'Rp', 'symbol_unicode' => 'Rp', 'position' => 'before', 'separator' => '.' ],
'56' => ['country_id' => 56, 'name' => 'Rials', 'code' => 'IRR', 'symbol' => 'ï·¼', 'symbol_unicode' => '&#65020;', 'position' => '', 'separator' => '.' ],
'57' => ['country_id' => 57, 'name' => 'Dinar', 'code' => 'IQD', 'symbol' => 'Ø¯.Ø¹', 'symbol_unicode' => '&#x062F;.&#x0639;', 'position' => 'after', 'separator' => '' ],
'58' => ['country_id' => 58, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => ',' ],
'59' => ['country_id' => 59, 'name' => 'Pounds', 'code' => 'IMP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'60' => ['country_id' => 60, 'name' => 'New Shekels', 'code' => 'ILS', 'symbol' => 'â‚ª', 'symbol_unicode' => '&#x20AA;', 'position' => 'before', 'separator' => '.' ],
'61' => ['country_id' => 61, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => '.' ],
'62' => ['country_id' => 62, 'name' => 'Dollars', 'code' => 'JMD', 'symbol' => 'J$', 'symbol_unicode' => 'J&#36;', 'position' => '', 'separator' => '.' ],
'63' => ['country_id' => 63, 'name' => 'Yen', 'code' => 'JPY', 'symbol' => 'Â¥', 'symbol_unicode' => '&#165;', 'position' => 'before', 'separator' => '.' ],
'64' => ['country_id' => 64, 'name' => 'Pounds', 'code' => 'JEP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'65' => ['country_id' => 65, 'name' => 'Dinar', 'code' => 'JOD', 'symbol' => 'Ø¯ÙŠÙ†Ø§Ø±', 'symbol_unicode' => '&#x062F;&#x064A;&#x0646;&#x0627;&#x0631;', 'position' => 'after', 'separator' => '' ],
'66' => ['country_id' => 66, 'name' => 'Tenge', 'code' => 'KZT', 'symbol' => 'Ð»Ð²', 'symbol_unicode' => '&#1083;&#1074;', 'position' => '', 'separator' => '.' ],
'67' => ['country_id' => 67, 'name' => 'Won', 'code' => 'KPW', 'symbol' => 'â‚©', 'symbol_unicode' => '&#x20A9;', 'position' => '', 'separator' => '.' ],
'68' => ['country_id' => 68, 'name' => 'Won', 'code' => 'KRW', 'symbol' => 'â‚©', 'symbol_unicode' => '&#x20A9;', 'position' => 'before', 'separator' => '.' ],
'69' => ['country_id' => 69, 'name' => 'Dinar', 'code' => 'KWD', 'symbol' => 'Ø¯ÙŠÙ†Ø§Ø±', 'symbol_unicode' => '&#x062F;&#x064A;&#x0646;&#x0627;&#x0631;', 'position' => 'after', 'separator' => '' ],
'70' => ['country_id' => 70, 'name' => 'Soms', 'code' => 'KGS', 'symbol' => 'Ð»Ð²', 'symbol_unicode' => '&#1083;&#1074;', 'position' => '', 'separator' => '.' ],
'71' => ['country_id' => 71, 'name' => 'Kips', 'code' => 'LAK', 'symbol' => 'â‚­', 'symbol_unicode' => '&#8365;', 'position' => '', 'separator' => '.' ],
'72' => ['country_id' => 72, 'name' => 'Lati', 'code' => 'LVL', 'symbol' => 'Ls', 'symbol_unicode' => 'Ls', 'position' => 'before', 'separator' => '.' ],
'73' => ['country_id' => 73, 'name' => 'Pounds', 'code' => 'LBP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'74' => ['country_id' => 74, 'name' => 'Dollars', 'code' => 'LRD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'75' => ['country_id' => 75, 'name' => 'Switzerland Francs', 'code' => 'CHF', 'symbol' => 'Fr.', 'symbol_unicode' => 'Fr.', 'position' => 'before', 'separator' => '.' ],
'76' => ['country_id' => 76, 'name' => 'Litai', 'code' => 'LTL', 'symbol' => 'Lt', 'symbol_unicode' => 'Lt', 'position' => 'before', 'separator' => '.' ],
'77' => ['country_id' => 77, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => '.' ],
'78' => ['country_id' => 78, 'name' => 'Denars', 'code' => 'MKD', 'symbol' => 'Ð´ÐµÐ½', 'symbol_unicode' => '&#1076;&#1077;&#1085;', 'position' => '', 'separator' => '.' ],
'79' => ['country_id' => 79, 'name' => 'Ringgits', 'code' => 'MYR', 'symbol' => 'RM', 'symbol_unicode' => 'RM', 'position' => 'before', 'separator' => '.' ],
'80' => ['country_id' => 80, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => ',' ],
'81' => ['country_id' => 81, 'name' => 'Rupees', 'code' => 'MUR', 'symbol' => 'â‚¨', 'symbol_unicode' => '&#8360;', 'position' => '', 'separator' => '.' ],
'82' => ['country_id' => 82, 'name' => 'Pesos', 'code' => 'MXN', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'83' => ['country_id' => 83, 'name' => 'Tugriks', 'code' => 'MNT', 'symbol' => 'â‚®', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'84' => ['country_id' => 84, 'name' => 'Meticais', 'code' => 'MZN', 'symbol' => 'MT', 'symbol_unicode' => 'MT', 'position' => '', 'separator' => '.' ],
'85' => ['country_id' => 85, 'name' => 'Dollars', 'code' => 'NAD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'86' => ['country_id' => 86, 'name' => 'Rupees', 'code' => 'NPR', 'symbol' => 'â‚¨', 'symbol_unicode' => '&#8360;', 'position' => '', 'separator' => '.' ],
'87' => ['country_id' => 87, 'name' => 'Guilders', 'code' => 'ANG', 'symbol' => 'Æ’', 'symbol_unicode' => '&fnof;', 'position' => '', 'separator' => '.' ],
'88' => ['country_id' => 88, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => ',' ],
'89' => ['country_id' => 89, 'name' => 'Dollars', 'code' => 'NZD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'90' => ['country_id' => 90, 'name' => 'Cordobas', 'code' => 'NIO', 'symbol' => 'C$', 'symbol_unicode' => 'C&#36;', 'position' => '', 'separator' => '.' ],
'91' => ['country_id' => 91, 'name' => 'Nairas', 'code' => 'NGN', 'symbol' => 'â‚¦', 'symbol_unicode' => '&#x20A6;', 'position' => 'before', 'separator' => '.' ],
'92' => ['country_id' => 92, 'name' => 'Won', 'code' => 'KPW', 'symbol' => 'â‚©', 'symbol_unicode' => '&#x20A9;', 'position' => '', 'separator' => '.' ],
'93' => ['country_id' => 93, 'name' => 'Krone', 'code' => 'NOK', 'symbol' => 'kr', 'symbol_unicode' => 'kr', 'position' => 'before', 'separator' => '.' ],
'94' => ['country_id' => 94, 'name' => 'Rials', 'code' => 'OMR', 'symbol' => 'ï·¼', 'symbol_unicode' => '&#65020;', 'position' => 'after', 'separator' => '.' ],
'95' => ['country_id' => 95, 'name' => 'Rupees', 'code' => 'PKR', 'symbol' => 'â‚¨', 'symbol_unicode' => '&#8360;', 'position' => '', 'separator' => '.' ],
'96' => ['country_id' => 96, 'name' => 'Balboa', 'code' => 'PAB', 'symbol' => 'B/.', 'symbol_unicode' => 'B/.', 'position' => '', 'separator' => '.' ],
'97' => ['country_id' => 97, 'name' => 'Guarani', 'code' => 'PYG', 'symbol' => 'Gs', 'symbol_unicode' => 'Gs', 'position' => '', 'separator' => '.' ],
'98' => ['country_id' => 98, 'name' => 'Nuevos Soles', 'code' => 'PEN', 'symbol' => 'S/.', 'symbol_unicode' => 'S/.', 'position' => 'before', 'separator' => '.' ],
'99' => ['country_id' => 99, 'name' => 'Pesos', 'code' => 'PHP', 'symbol' => 'Php', 'symbol_unicode' => '&#x20B1;', 'position' => 'before', 'separator' => '.' ],
'100' => ['country_id' => 100, 'name' => 'Zlotych', 'code' => 'PLN', 'symbol' => 'zÅ‚', 'symbol_unicode' => 'Z&#322;', 'position' => 'before', 'separator' => '.' ],
'101' => ['country_id' => 101, 'name' => 'Rials', 'code' => 'QAR', 'symbol' => 'ï·¼', 'symbol_unicode' => '&#65020;', 'position' => 'after', 'separator' => '.' ],
'102' => ['country_id' => 102, 'name' => 'New Lei', 'code' => 'RON', 'symbol' => 'lei', 'symbol_unicode' => 'lei', 'position' => 'before', 'separator' => '.' ],
'103' => ['country_id' => 103, 'name' => 'Rubles', 'code' => 'RUB', 'symbol' => 'Ñ€ÑƒÐ±', 'symbol_unicode' => '&#1088;&#1091;&#1073;', 'position' => 'after', 'separator' => '.' ],
'104' => ['country_id' => 104, 'name' => 'Pounds', 'code' => 'SHP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'105' => ['country_id' => 105, 'name' => 'Riyals', 'code' => 'SAR', 'symbol' => 'ï·¼', 'symbol_unicode' => '&#65020;', 'position' => 'after', 'separator' => '.' ],
'106' => ['country_id' => 106, 'name' => 'Dinars', 'code' => 'RSD', 'symbol' => 'Ð”Ð¸Ð½.', 'symbol_unicode' => '&#1044;&#1080;&#1085;&#46;', 'position' => '', 'separator' => '.' ],
'107' => ['country_id' => 107, 'name' => 'Rupees', 'code' => 'SCR', 'symbol' => 'â‚¨', 'symbol_unicode' => '&#8360;', 'position' => '', 'separator' => '.' ],
'108' => ['country_id' => 108, 'name' => 'Dollars', 'code' => 'SGD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'109' => ['country_id' => 109, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => ',' ],
'110' => ['country_id' => 110, 'name' => 'Dollars', 'code' => 'SBD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'111' => ['country_id' => 111, 'name' => 'Shillings', 'code' => 'SOS', 'symbol' => 'S', 'symbol_unicode' => 'S', 'position' => '', 'separator' => '.' ],
'112' => ['country_id' => 112, 'name' => 'Rand', 'code' => 'ZAR', 'symbol' => 'R', 'symbol_unicode' => 'R', 'position' => 'before', 'separator' => '.' ],
'113' => ['country_id' => 113, 'name' => 'Won', 'code' => 'KRW', 'symbol' => 'â‚©', 'symbol_unicode' => '&#8361;', 'position' => '', 'separator' => '.' ],
'114' => ['country_id' => 114, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&euro;', 'position' => '', 'separator' => ',' ],
'115' => ['country_id' => 115, 'name' => 'Rupees', 'code' => 'LKR', 'symbol' => 'â‚¨', 'symbol_unicode' => '&#8360;', 'position' => '', 'separator' => '.' ],
'116' => ['country_id' => 116, 'name' => 'Kronor', 'code' => 'SEK', 'symbol' => 'kr', 'symbol_unicode' => 'kr', 'position' => 'before', 'separator' => '.' ],
'117' => ['country_id' => 117, 'name' => 'Francs', 'code' => 'CHF', 'symbol' => 'CHF', 'symbol_unicode' => 'CHF', 'position' => '', 'separator' => '.' ],
'118' => ['country_id' => 118, 'name' => 'Dollars', 'code' => 'SRD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'119' => ['country_id' => 119, 'name' => 'Pounds', 'code' => 'SYP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'120' => ['country_id' => 120, 'name' => 'New Dollars', 'code' => 'TWD', 'symbol' => 'NT$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'121' => ['country_id' => 121, 'name' => 'Baht', 'code' => 'THB', 'symbol' => 'à¸¿', 'symbol_unicode' => '&#3647;', 'position' => 'before', 'separator' => '.' ],
'122' => ['country_id' => 122, 'name' => 'Dollars', 'code' => 'TTD', 'symbol' => 'TT$', 'symbol_unicode' => '&#36;', 'position' => 'before', 'separator' => '.' ],
'123' => ['country_id' => 123, 'name' => 'Lira', 'code' => 'TRY', 'symbol' => 'TL', 'symbol_unicode' => 'TL', 'position' => 'before', 'separator' => '.' ],
'124' => ['country_id' => 124, 'name' => 'Dollars', 'code' => 'TVD', 'symbol' => '$', 'symbol_unicode' => '&#36;', 'position' => '', 'separator' => '.' ],
'125' => ['country_id' => 125, 'name' => 'Hryvnia', 'code' => 'UAH', 'symbol' => 'â‚´', 'symbol_unicode' => '&#8372;', 'position' => 'before', 'separator' => '.' ],
'126' => ['country_id' => 126, 'name' => 'Pounds', 'code' => 'GBP', 'symbol' => 'Â£', 'symbol_unicode' => '&pound;', 'position' => '', 'separator' => '.' ],
'127' => ['country_id' => 127, 'name' => 'Pesos', 'code' => 'UYU', 'symbol' => '$U', 'symbol_unicode' => '&#36;U', 'position' => '', 'separator' => '.' ],
'128' => ['country_id' => 128, 'name' => 'Sums', 'code' => 'UZS', 'symbol' => 'Ð»Ð²', 'symbol_unicode' => '&#1083;&#1074;', 'position' => '', 'separator' => '.' ],
'129' => ['country_id' => 129, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => 'â‚¬', 'symbol_unicode' => '&#128;', 'position' => 'before', 'separator' => ',' ],
'130' => ['country_id' => 130, 'name' => 'Bolivares Fuertes', 'code' => 'VEF', 'symbol' => 'Bs', 'symbol_unicode' => 'Bs.', 'position' => 'before', 'separator' => '.' ],
'131' => ['country_id' => 131, 'name' => 'Dong', 'code' => 'VND', 'symbol' => 'â‚«', 'symbol_unicode' => '&#x20AB;', 'position' => 'before', 'separator' => '.' ],
'132' => ['country_id' => 132, 'name' => 'Rials', 'code' => 'YER', 'symbol' => 'ï·¼', 'symbol_unicode' => '&#65020;', 'position' => '', 'separator' => '.' ],
'133' => ['country_id' => 133, 'name' => 'Zimbabwe Dollars', 'code' => 'ZWD', 'symbol' => 'Z$', 'symbol_unicode' => 'Z&#36;', 'position' => '', 'separator' => '.' ],
'134' => ['country_id' => 134, 'name' => 'Dirham', 'code' => 'AED', 'symbol' => 'Ø¯.Ø¥;', 'symbol_unicode' => '&#x062F;.&#x0625;;', 'position' => 'after', 'separator' => ',' ]
		];
		foreach ( $currency as $key => $value ) {
			Currency::create ( [
					'id' => $key,
					'country_id'=>$value ['country_id'],
					'name' => $value ['name'],
					'code' => $value ['code'],
					'symbol'=> $value['symbol'],
					'symbol_unicode' => $value['symbol_unicode'],
					'position' => $value['position'],
					'separator' => $value['separator'],
			] );
		}
	}
}
